- category: general-metadata
  requirements:
    - metadata/traceability-sr
  # todo: the following should probably be added to the requirements
  # - metadata/license
- category: source-metadata
  requirements:
    - example
- category: product-metadata
  requirements:
  # todo: the following should probably be added to the requirements
  # - metadata/product-type
    - example
- category: per-pixel-metadata
  requirements:
    - example
- category: radiometric-atmospheric-corrections
  requirements:
    - measurements/uncertainty-sr # 3.2
- category: geometric-corrections
  requirements:
    - example