- category: general-metadata
  requirements:
    - metadata/traceability-sr
    - metadata/machine-readability-optical
    - metadata/time-sr
    - metadata/geo-area-sr
    - metadata/crs-optical
    - metadata/map-projection-nlsr
    - metadata/geometric-correction-methods-sr
    - metadata/geometric-accuracy-sr
    - metadata/instrument-optical
    - metadata/spectral-bands
    - metadata/sensor-calibration-optical
    - metadata/radiometric-accuracy-sr
    - metadata/algorithms-sr
    - metadata/auxiliary-data-optical
    - metadata/processing-chain-prov-nlsr
    - metadata/data-access
    - metadata/data-quality-sr
- category: per-pixel-metadata
  requirements:
    - metadata/machine-readability-per-pixel-optical
    - per-pixel/nodata
    - per-pixel/incomplete-testing
    - per-pixel/saturation
    - per-pixel/cloud
    - per-pixel/cloud-shadow-nlsr
    - per-pixel/land-water-nlsr
    - per-pixel/snow-ice-nlsr
    - per-pixel/terrain-shadow
    - per-pixel/terrain-occlusion
    - per-pixel/view-angles-lunar
    - per-pixel/terrain-illumination
    - per-pixel/moon-illumination-fraction
    - per-pixel/brightness-temperature
    - per-pixel/solar-zenith-angle
- category: radiometric-atmospheric-corrections
  requirements:
    - measurements/measurement-nlsr
    - measurements/uncertainty-sr
    - measurements/normalisation-nlsr
    - measurements/atmospheric-corrections
    - corrections/lunar-radiance
    - corrections/stray-light
- category: geometric-corrections
  requirements:
    - corrections/geometric-sr