- category: general-metadata
  requirements:
    - metadata/traceability-st
    - metadata/machine-readability
  # todo: the following should probably be added to the requirements
  # - metadata/license
- category: source-metadata
  requirements:
    - metadata/time
- category: product-metadata
  requirements:
    - example
  # todo: the following should probably be added to the requirements
  # - metadata/product-type
- category: per-pixel-metadata
  requirements:
    - example
- category: radiometric-atmospheric-corrections
  requirements:
    - measurements/uncertainty-st # 3.3
- category: geometric-corrections
  requirements:
    - corrections/geometric-corrections