- category: general_metadata
  requirements:
    - metadata/traceability-st
    - metadata/machine-readability
    # todo: the following should probably be added to the requirements
    # - metadata/product-type
    # - metadata/license
    - metadata/time
- category: source_metadata
  requirements:
    - example/example
- category: per_pixel_metadata
  requirements:
    - example/example
- category: radiometric_atmospheric_corrections
  requirements:
    - example/example
- category: geometric_corrections
  requirements:
    - example/example