- category: general-metadata
  requirements:
    - metadata/traceability-st
    - metadata/machine-readability-optical
    - metadata/time-st
    - metadata/geo-area-st
    - metadata/crs-optical
    - metadata/map-projection-st
    - metadata/geometric-correction-methods-st
    - metadata/geometric-accuracy-st
    - metadata/instrument-optical
    - metadata/spectral-bands
    - metadata/sensor-calibration-optical
    - metadata/radiometric-accuracy-st
    - metadata/algorithms
    - metadata/auxiliary-data-optical
    - metadata/processing-chain-prov-st
    - metadata/data-access
    - metadata/data-quality-st
- category: per-pixel-metadata
  requirements:
    - metadata/machine-readability-per-pixel-optical
    - per-pixel/nodata
    - per-pixel/incomplete-testing
    - per-pixel/saturation
    - per-pixel/cloud
    - per-pixel/cloud-shadow
    - per-pixel/snow-ice-sr
    - per-pixel/view-angles-solar
- category: radiometric-atmospheric-corrections
  requirements:
    - measurements/measurement-st
    - corrections/atmosphere-emissivity
    - measurements/uncertainty-st
- category: geometric-corrections
  requirements:
    - corrections/geometric-st