settings:
  bullet: '-'
plugins:
# GitHub Flavored Markdown
  - remark-gfm
  - - remark-frontmatter
    - type: yaml
      marker: '-'
# Math
  - remark-math
# Check links
  - validate-links
# Apply some recommended defaults for consistency
  - remark-preset-lint-consistent
  - remark-preset-lint-recommended
  - lint-no-html
# General formatting
  - remark-lint-no-undefined-references
  - remark-lint-hard-break-spaces
  - remark-lint-blockquote-indentation
# Code
  - remark-lint-fenced-code-flag
  - remark-lint-fenced-code-marker
  - remark-lint-no-shell-dollars
  - - remark-lint-code-block-style
    - 'fenced'
# Headings
  - remark-lint-heading-increment
  - remark-lint-no-multiple-toplevel-headings
  - - remark-lint-maximum-heading-length
    - 70
  - - remark-lint-heading-style
    - atx
  - - remark-lint-no-shortcut-reference-link
    - false
# Lists
  - remark-lint-list-item-bullet-indent
  - remark-lint-ordered-list-marker-style
  - remark-lint-ordered-list-marker-value
  - remark-lint-checkbox-character-style
  - - remark-lint-unordered-list-marker-style
    - '-'
  - - remark-lint-list-item-indent
    - one
# Tables
  - remark-lint-table-pipes
  - remark-lint-no-literal-urls
