name: Optical - All Products
description: Report an issue or propose a change for the Optical PFSes, which applies to more than one product type.
labels:
  - Optical
  - needs discussion
body:
  - type: input
    id: version
    attributes:
      label: PFS Version(s)
      description: What version(s) of the PFSes are you referring to?
      placeholder: "e.g. 5.0.1"
  - type: input
    id: req-no
    attributes:
      label: Requirement number(s)
      description: Which requirement number(s) are you referring to?
      placeholder: "e.g. 1.6"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the issue or proposal.
      placeholder: Add your description here...
    validations:
      required: true

