- category: general-metadata
  requirements:
    # todo: most of the general metadata is product metadata - this should potentially be merged.
    - metadata/traceability-sar
    - metadata/machine-readability-sar
    - metadata/product-type-sar
    - metadata/pfs-url
    - metadata/time-sar
- category: source-metadata
  requirements:
    - metadata/acquisition-id # todo: this is new from the category description
    - metadata/data-access-source
    - metadata/instrument-sar
    - metadata/time-source
    - metadata/acquisition-parameters-sar
    - metadata/orbit
    - metadata/processing-parameters
    - metadata/image-attributes-sar
    - metadata/sensor-calibration-sar
    - metadata/performance-indicators
    - metadata/polarimetric-calibration-matrices
    - metadata/mean-faraday-rotation-angle
    - metadata/ionosphere-indicator
- category: product-metadata
  requirements:
    - metadata/data-access-product
    - metadata/auxiliary-data
    - metadata/sample-spacing
    - metadata/resolution
    - metadata/geo-bbox
    - metadata/geo-area
    - metadata/image-size
    - metadata/pixel-coordinate-convention
    - metadata/crs
    - metadata/radar-unit-look-vector
    - metadata/slant-range
    - metadata/orbit-reference-gslc
- category: per-pixel-metadata
  requirements:
    - cloud-optimized-formats
    - metadata/machine-readability-sar
    - per-pixel/data-mask
    - per-pixel/scattering-area
    - per-pixel/local-incident-angle
    - per-pixel/ellipsoidal-incident-angle
    - per-pixel/noise-power
    - per-pixel/gamma-sigma-ratio
    - per-pixel/acquisition-id
    - per-pixel/dem
    - per-pixel/radar-unit-look-vector-grid
    - per-pixel/slant-range
    - per-pixel/insar-phase-uncertainty
    - per-pixel/atmospheric-phase-correction
    - per-pixel/ionospheric-phase-correction
- category: radiometrically-corrected-measurements
  requirements:
    - cloud-optimized-formats
    - measurements/backscatter-gslc
    - metadata/scaling-conversion
    - metadata/noise-removal
    - corrections/radiometric-terrain-algo-gslc
    - metadata/radiometric-accuracy-sar
- category: geometric-corrections
  requirements:
    - metadata/geometric-correction-algorithm
    - corrections/dem
    - corrections/geometric-accuracy-radar
    - corrections/geometric-refined-accuracy
    - corrections/gridding-convention