- category: general-metadata
  requirements:
    # todo: most of the general metadata is product metadata - this should potentially be merged.
    - metadata/traceability
    - metadata/machine-readability
    - metadata/product-type
    - metadata/license
    - metadata/pfs-url
    - metadata/time
- category: source-metadata
  requirements:
    - metadata/sequential-id # todo: this is new from the category description
    - metadata/data-access-source
    - metadata/instrument
    - metadata/time-source
    - metadata/acquisition-parameters-sar
    - metadata/orbit
    - metadata/processing-parameters
    - metadata/image-attributes-sar
    - metadata/sensor-calibration
    - metadata/performance-indicators
    - metadata/polarimetric-calibration-matrices
    - metadata/mean-faraday-rotation-angle
    - metadata/ionosphere-indicator
- category: product-metadata
  requirements:
    - metadata/data-access-product
    - metadata/auxiliary-data
    - metadata/sample-spacing
    - metadata/enl
    - metadata/resolution
    - metadata/speckle-filtering
    - metadata/bounding-box
    - metadata/footprint
    - metadata/image-size
    - metadata/pixel-coordinate-convention
    - metadata/crs
    - metadata/look-direction-polynomials
- category: per-pixel-metadata
  requirements:
    - cloud-optimized-formats
    - per-pixel-metadata/acquisition-id # 2.8
    - per-pixel-metadata/look-direction # 2.11
- category: radiometrically-corrected-measurements
  requirements:
    - cloud-optimized-formats
    - measurements/backscatter-orb # 3.1
    - measurements/mean-wind-normalised-backscatter # 3.6
- category: geometric-corrections
  requirements:
    - metadata/geometric-correction-algorithm # 4.1
    - corrections/dem