- category: general-metadata
  requirements:
    - metadata/traceability-sr
    - metadata/machine-readability-optical
    - metadata/time-sr
    - metadata/geo-area-sr
    - metadata/crs-optical
    - metadata/map-projection-sr
    - metadata/geometric-correction-methods-sr
    - metadata/geometric-accuracy-sr
    - metadata/instrument-optical
    - metadata/spectral-bands
    - metadata/sensor-calibration-optical
    - metadata/radiometric-accuracy-sr
    - metadata/algorithms-sr
    - metadata/auxiliary-data-optical
    - metadata/processing-chain-prov-sr
    - metadata/data-access
    - metadata/data-quality-sr
- category: per-pixel-metadata
  requirements:
    - metadata/machine-readability-per-pixel-optical
    - per-pixel/nodata
    - per-pixel/incomplete-testing
    - per-pixel/saturation
    - per-pixel/cloud
    - per-pixel/cloud-shadow
    - per-pixel/land-water
    - per-pixel/snow-ice
    - per-pixel/terrain-shadow
    - per-pixel/terrain-occlusion
    - per-pixel/solar-view-angles
    - per-pixel/terrain-illumination
- category: radiometric-atmospheric-corrections
  requirements:
    - measurements/measurement-sr
    - measurements/uncertainty-sr
    - measurements/normalisation-sr
    - measurements/directional-atmospheric-scattering
    - corrections/water-vapour
    - corrections/ozone
- category: geometric-corrections
  requirements:
    - corrections/geometric-sr