- category: general-metadata
  requirements:
    - metadata/traceability
    - metadata/machine-readability
    # todo: the following should probably be added to the requirements
    # - metadata/product-type
    # - metadata/license
    - metadata/time
- category: source-metadata
  requirements:
    - example
- category: per-pixel-metadata
  requirements:
    - example
- category: radiometric-atmospheric-corrections
  requirements:
    - example
- category: geometric-corrections
  requirements:
    - example