- category: general-metadata
  requirements:
    - metadata/traceability
    - metadata/machine-readability-sar
    - metadata/license
- category: source-metadata
  requirements:
    - metadata/time-sar
- category: product-metadata
  requirements:
    - metadata/product-type
    - metadata/bounding-box
    - metadata/crs
- category: per-pixel-metadata
  requirements:
    - cloud-optimized-formats
- category: radiometrically-corrected-measurements
  requirements:
    - cloud-optimized-formats
- category: geometric-corrections
  requirements:
    - example