- category: general-metadata
  requirements:
    # todo: most of the general metadata is product metadata - this should potentially be merged.
    - metadata/traceability-sar
    - metadata/machine-readability
    - metadata/product-type-sar
    - metadata/pfs-url
    - metadata/time
- category: source-metadata
  requirements:
    - metadata/acquisition-id # todo: this is new from the category description
    - metadata/data-access-source
    - metadata/instrument
    - metadata/time-source
    - metadata/acquisition-parameters-sar
    - metadata/orbit
    - metadata/processing-parameters
    - metadata/image-attributes-sar
    - metadata/sensor-calibration
    - metadata/performance-indicators
    - metadata/polarimetric-calibration-matrices
    - metadata/mean-faraday-rotation-angle
    - metadata/ionosphere-indicator
- category: product-metadata
  requirements:
    - metadata/data-access-product
    - metadata/auxiliary-data
    - metadata/sample-spacing
    - metadata/enl
    - metadata/resolution
    # todo: speckle-filtering-pol should be just be speckle-filtering and instead add pol-filtering
    - metadata/speckle-filtering-pol
    # - metadata/pol-filtering
    - metadata/geo-bbox
    - metadata/geo-area
    - metadata/image-size
    - metadata/pixel-coordinate-convention
    - metadata/crs
    - metadata/orbit-reference-nrb-pol
- category: per-pixel-metadata
  requirements:
    # - cloud-optimized-formats
    - metadata/machine-readability
    - per-pixel/data-mask
    - per-pixel/scattering-area
    - per-pixel/local-incident-angle
    - per-pixel/ellipsoidal-incident-angle
    - per-pixel/noise-power
    - per-pixel/gamma-sigma-ratio
    - per-pixel/acquisition-id
    - per-pixel/dem
- category: radiometrically-corrected-measurements
  requirements:
    # - cloud-optimized-formats
    - measurements/backscatter-pol
    - metadata/scaling-conversion
    - metadata/noise-removal
    - corrections/radiometric-terrain-algo
    - metadata/radiometric-accuracy
    - measurements/flattened-phase
- category: geometric-corrections
  requirements:
    - metadata/geometric-correction-algorithm
    - corrections/dem
    - corrections/geometric-accuracy-radar
    - corrections/geometric-refined-accuracy
    - corrections/gridding-convention