- category: general-metadata
  requirements:
    - metadata/traceability
    - metadata/machine-readability-sar
    - metadata/license
- category: source-metadata
  requirements:
    - metadata/sequential-id
    - metadata/time-sar
- category: product-metadata
  requirements:
    - metadata/product-type
    - metadata/bounding-box
    - metadata/crs
- category: per-pixel-metadata
  requirements:
    - cloud-optimized-formats
    - per-pixel-metadata/acquisition-id # 2.8
- category: radiometrically-corrected-measurements
  requirements:
    - cloud-optimized-formats
    - measurements/backscatter-pol # 3.1
    - measurements/flattened-phase # 3.7
- category: geometric-corrections
  requirements:
    - example