id: prdtyp
title: Product Type
description: 
requirements:
  threshold:
    description: |-
      CEOS-ARD product type name – or names in case of compliance with more than one product type – and, if required by the data provider, copyright.
dependencies:
glossary:
references:
changes:
history:
  - SAR 1.3
