title: Product Type
description:
threshold:
  # todo: split into product-type and copyright as two requirements were mixed into one requirement before.
  # todo: Merged 1.3 and 1.4 into one as they seem closely related, especially that we don't created combined PFSes any longer.
  description: |-
    - CEOS-ARD product type name
    - Reference to CEOS-ARD PFS document as URL
  notes:
    - In case of compliance with more than one product type, multiple product type names and URLs must be provided.
goal: null
glossary:
references:
metadata:
legacy:
  sar: 1.3 & 1.4
  optical: null
