- title: General Metadata
  description: >-
    These are metadata records describing a distributed collection of pixels.
    The collection of pixels referred to must be contiguous in space and time.
    General metadata should allow the user to assess the overall suitability of the dataset and
    must meet the requirements listed below.
    The column “CEOS-ARD product” indicates to which CEOS-ARD SAR product (NRB, POL, ORB, GSLC)
    the parameter refers.
  requirements:
    - metadata/traceability
    - metadata/machine-readability
    - ...
    - satellite/instrument
    - ...
- title: Per-Pixel Metadata
  description: ...
  requirements:
    - metadata/machine-readability
    - ...