name: CI
on:
  - push
  - pull_request
jobs:
  deploy-pr:
    if: github.event.number
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: https://ceos-ard-preview.mohr.ws/pr-${{ github.event.number }}
    steps:
      - name: Download PFS artifacts
        uses: actions/download-artifact@v4
        with:
          name: documents
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: documents/
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.ceos-ard-preview.mohr.ws
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: documents/
          server-dir: pr-${{ github.event.number }}/
          exclude: '{assets/**,*.{md,bib}}'
          dangerous-clean-slate: true
      - name: Add comment to pull request
        uses: actions/github-script@v7
        with:
          script: |
            const pullRequestNumber = ${{ github.event.number }};
            const start = '⚠️';
            const author = 'github-actions[bot]';

            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequestNumber
            });

            const commentExists = comments.data.some(
              comment => comment.user.login === author && comment.body.startsWith(start)
            );

            if (!commentExists) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pullRequestNumber,
                body: `${start} A preview for all PFS has been generated and can be accessed here: <https://ceos-ard-preview.mohr.ws/pr-${pullRequestNumber}/>`
              });
            } else {
              console.log(`Preview URL comment already added to PR #${pullRequestNumber}`);
            }